### PR TITLE
fix windows short path alias 8.3

### PR DESCRIPTION
**Pull request by patricklx**

### CODE REVIEW

**Comment by ef4** [comment]
This seems like a bug in the very-old `tmp` package that is generating these paths. I don't think this kind of workaround belongs in scenario-tester.

**Comment by patricklx** [comment]
> This seems like a bug in the very-old `tmp` package that is generating these paths. I don't think this kind of workaround belongs in scenario-tester.

mm, i did not find any open issues about it. i'm talking about this:
https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#short-vs-long-names

its a windows thing. tmp package does not have control over that. it can be disabled via windows registry... but thats not possible on github runners. it should really be disabled by default.

there is some discussion here as well: https://github.com/actions/runner-images/issues/712

**Comment by patricklx** [comment]
maybe we can just change the TEMP var:
https://stackoverflow.com/a/39259598

**Comment by ef4** [comment]
Some global fix like that would be better. Because I doubt this is the only spot that would be unhappy about being unable to rely on a canonical path being consistent. This same kind of thing would definitely break the PackageCache, for example. If you search for all the places that embroider uses realpathSync you'll see several examples.

**Comment by patricklx** [comment]
> Some global fix like that would be better. Because I doubt this is the only spot that would be unhappy about being unable to rely on a canonical path being consistent. This same kind of thing would definitely break the PackageCache, for example. If you search for all the places that embroider uses realpathSync you'll see several examples.

The global fix would only work for tmp.
I do not think realpathsync does have the issue. I would probably already have seen it if it does.
It mostly does string manipulation. Only fir symlinks it uses os calls. Which should be save as long as the project is setup within a non short path.

**Pull request closed without merging**
